import { expect, test } from '@playwright/test'
import { GUEST_BLANK_QR_ID, GUEST_DESK_QR_ID, GUEST_PC_QR_ID } from '../src/lib/guest/seed'
import { expectNoHqLeftovers } from './helpers'

test('게스트 홈 카드는 샘플 업무만 연다', async ({ page }) => {
  await page.goto('/guest')
  await expect(page.getByRole('heading', { name: '샘플 회사' })).toBeVisible()
  const cards = [
    [/입고·반출·재고현황/, '/guest/stock', '구매·재고'],
    [/빈 QR과 자리의 물건/, '/guest/assets', '자산'],
    [/견본 김대리/, '/guest/people', '직원·입퇴사'],
    [/샘플 사무실 임대/, '/guest/contracts', '계약'],
    [/부서·품목·창고/, '/guest/master', '기준정보'],
  ] as const
  for (const [hint, href, heading] of cards) {
    await page.goto('/guest')
    await page.getByRole('link', { name: hint }).click()
    await expect(page).toHaveURL(href)
    await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible({ timeout: 20000 })
    await expectNoHqLeftovers(page)
  }
})

test('게스트 기준정보 부서·창고·직원은 샘플만 둔다', async ({ page }) => {
  await page.goto('/guest/master')
  await expect(page.getByRole('heading', { name: '기준정보' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '부서', exact: true }).click()
  await expect(page.getByText('샘플총무')).toBeVisible()
  await page.getByRole('button', { name: '창고', exact: true }).click()
  await expect(page.getByText('샘플창고')).toBeVisible()
  await expect(page.getByText('본사창고')).toHaveCount(0)
  await page.getByRole('button', { name: '직원', exact: true }).click()
  await expect(page.getByText('견본 김대리')).toBeVisible()
  await expect(page.getByText('김담당')).toHaveCount(0)
})

test('게스트 입퇴사 탭은 견본만 두고 본사 사람을 두지 않는다', async ({ page }) => {
  await page.goto('/guest/people')
  await expect(page.getByRole('heading', { name: '직원·입퇴사' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: /^입사 중/ }).click()
  await expect(page.getByRole('button', { name: /견본 김대리/ })).toBeVisible()
  await expect(page.getByText('G-101').first()).toBeVisible()
  await expect(page.getByRole('button', { name: /데모 이사원/ })).toBeVisible()
  await page.getByRole('button', { name: /^퇴사/ }).click()
  await expect(page.getByRole('button', { name: /견본 최과장/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^재직/ })).toHaveCount(0)
  await expect(page.getByText('김담당')).toHaveCount(0)
  await expect(page.getByText('지급 전 · 입사 중 프로세스부터')).toHaveCount(0)
})

test('게스트 재고 명령 여러 개는 영어와 본사 잔재를 두지 않는다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '발주·검수 더 보기' }).click()
  const commands = [
    ...['post_direct_in', 'post_issue', 'post_return'],
    ...['confirm_order', 'post_receipt', 'post_supplier_return', 'draft_order', 'post_outbound', 'transfer_stock', 'adjust_stock', 'reverse_transaction', 'convert_to_asset'],
  ] as const
  for (const command of commands) {
    await page.getByLabel('명령').selectOption(command)
    await expectNoHqLeftovers(page)
    await expect(page.getByText(/operation_id/)).toHaveCount(0)
    await expect(page.getByText('반납 가능 0')).toHaveCount(0)
    await expect(page.getByText('반품 가능 0')).toHaveCount(0)
    await expect(page.getByText('잔량 0')).toHaveCount(0)
    await expect(page.getByText('미수령 0')).toHaveCount(0)
    await expect(page.getByText('미발주 0')).toHaveCount(0)
    await expect(page.getByRole('heading', { name: '불량 0' })).toHaveCount(0)
    await expect(page.getByRole('heading', { name: '반납 기한 0' })).toHaveCount(0)
    await expect(page.getByRole('heading', { name: '납기 지남 0' })).toHaveCount(0)
  }
})

test('게스트 입고는 저장하고 영어 거래 번호를 두지 않는다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByLabel('명령').selectOption('post_direct_in')
  await expect(page.getByText('발주·요청 없이 현재고만 늘립니다.')).toBeVisible()
  await expect(page.getByLabel('발주 번호')).toHaveCount(0)
  await page.getByPlaceholder('이름을 치세요').fill('샘플 복사용지')
  await page.getByLabel('수량').fill('1')
  await expect(page.getByText('현재고 7 · 확정 후 8')).toBeVisible()
  await page.getByLabel('공급사').selectOption('견본문구')
  await page.getByLabel('입고 사유').fill('샘플 보충')
  await page.getByLabel('입고일').fill('2026-10-01')
  await page.getByLabel('메모').fill('샘플 메모')
  await page.getByLabel('입고 증빙').setInputFiles({
    name: '견본입고.png',
    mimeType: 'image/png',
    buffer: Buffer.from([0x89, 0x50, 0x4e, 0x47]),
  })
  await page.getByRole('button', { name: '입고', exact: true }).click()
  await expect(page.getByText('저장했습니다. (입고)')).toBeVisible()
  await expect(page.getByRole('button', { name: '샘플창고 현재고 8' })).toBeVisible()
  await expect(page.getByText('견본문구 · 샘플 보충 · 입고 2026-10-01 · 샘플 메모 · 견본입고.png')).toBeVisible()
  await expect(page.getByRole('cell', { name: '샘플 복사용지 · 박스 · 일반 비품' })).toHaveCount(2)
  await expect(page.getByText(/등록 /)).toHaveCount(0)
  await expect(page.getByText('단위 박스')).toBeVisible()
  await expect(page.getByRole('heading', { name: '발주 기록 0' })).toHaveCount(0)
  await expect(page.getByText(/operation_id/)).toHaveCount(0)
  await expect(page.getByText('김담당')).toHaveCount(0)
})

test('게스트 직접 입고 반품은 발주 없이 원입고만 줄인다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('cell', { name: '입고', exact: true }).click()
  await page.getByRole('button', { name: '발주·검수 더 보기' }).click()
  await page.getByLabel('명령').selectOption('post_supplier_return')
  await expect(page.getByLabel('발주 번호')).toHaveCount(0)
  await expect(page.getByText('원입고를 골라 공급사에 돌려 보냅니다.')).toBeVisible()
  await expect(page.getByText('반품 가능 7')).toBeVisible()
  await page.getByLabel('수량', { exact: true }).fill('1')
  await expect(page.getByText('현재고 7 · 확정 후 6')).toBeVisible()
  await page.getByRole('button', { name: '공급사 반품' }).click()
  await expect(page.getByText('저장했습니다. (공급사 반품)')).toBeVisible()
  await expect(page.getByRole('button', { name: '샘플창고 현재고 6' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '원입고', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '발주 기록 0' })).toHaveCount(0)
  await expect(page.getByText('반품 가능 0')).toHaveCount(0)
  await expectNoHqLeftovers(page)
})

test('게스트 계약 초안은 본사 김담당 없이 저장한다', async ({ page }) => {
  await page.goto('/guest/contracts')
  await expect(page.getByRole('heading', { name: '계약' }).first()).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('heading', { name: '샘플 사무실 임대' })).toBeVisible()
  await expect(page.getByText(/기한 알림/)).toBeVisible()
  await expect(page.getByRole('link', { name: '견본임대' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'ORD-DEMO-01' })).toBeVisible()
  await expect(page.getByRole('heading', { name: /인식 근거/ })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '인식 근거 0' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '다시 읽기' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '그만 읽기' })).toHaveCount(0)
  await expect(page.getByLabel('원본과 칸을 확인했습니다')).toHaveCount(0)
  await expect(page.getByText('PDF·PNG·JPEG 8MB · OCR 2쪽')).toBeVisible()
  await page.getByRole('button', { name: /^만료 예정/ }).click()
  await expect(page.getByRole('heading', { name: '샘플 보험' })).toBeVisible()
  await page.getByRole('button', { name: '새 초안' }).click()
  await page.getByLabel('계약명').fill('샘플 청소 계약')
  await page.getByLabel('상대방').fill('견본청소')
  await page.getByRole('button', { name: '초안 저장' }).click()
  await expect(page.getByText('계약 초안을 저장했습니다.')).toBeVisible()
  await expect(page.getByText('김담당')).toHaveCount(0)
})

test('게스트 같은 이름 초안은 개정 이력을 남긴다', async ({ page }) => {
  await page.goto('/guest/contracts')
  await expect(page.getByRole('heading', { name: '계약' }).first()).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '새 초안' }).click()
  await page.getByLabel('계약명').fill('샘플 사무실 임대')
  await page.getByLabel('상대방').fill('견본임대')
  await page.getByLabel('종료일').fill('2027-12-31')
  await expect(page.getByRole('button', { name: '초안 저장' })).toHaveCount(0)
  await page.getByRole('button', { name: '기존을 개정' }).click()
  await expect(page.getByText('기존 초안을 개정했습니다.')).toBeVisible()
  await expect(page.getByRole('heading', { name: /개정 이력/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: '개정 이력 0' })).toHaveCount(0)
  await expect(page.getByText('김담당')).toHaveCount(0)
})

test('게스트 재고 부족은 최소보다 적은 비품만 보여 준다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('heading', { name: /재고 부족/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /샘플 복사용지 7 \/ 최소 10/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: '재고 부족 0' })).toHaveCount(0)
})

test('게스트 현재고는 창고별 수량을 보여 준다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('columnheader', { name: '샘플창고' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: '견본창고' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: '합계' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '재고현황 0' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '원거래로' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '샘플창고 현재고 7' })).toBeVisible()
  await expect(page.getByRole('button', { name: '견본창고 현재고 0' })).toBeVisible()
  await page.getByRole('button', { name: '견본창고 현재고 0' }).click()
  await expect(page.getByRole('button', { name: '견본창고 현재고 0' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('combobox', { name: '창고' })).toHaveValue('wh-sub')
  await expectNoHqLeftovers(page)
})

test('게스트 창고 이동은 합계를 그대로 둔다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '발주·검수 더 보기' }).click()
  await page.getByLabel('명령').selectOption('transfer_stock')
  await expect(page.getByText('회사 합계는 그대로입니다.')).toBeVisible()
  await page.getByPlaceholder('이름을 치세요').fill('샘플 복사용지')
  await page.getByLabel('보내는 창고').selectOption({ label: '샘플창고' })
  await page.getByLabel('받는 창고').selectOption({ label: '견본창고' })
  await page.getByLabel('수량', { exact: true }).fill('2')
  await expect(page.getByText('보내는 현재고 7 · 확정 후 5 · 받는 현재고 0 · 확정 후 2')).toBeVisible()
  await page.getByRole('button', { name: '이동', exact: true }).click()
  await expect(page.getByText('저장했습니다. (이동)')).toBeVisible()
  await expect(page.getByRole('button', { name: '샘플창고 현재고 5' })).toBeVisible()
  await expect(page.getByRole('button', { name: '견본창고 현재고 2' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: '합계' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '재고현황 0' })).toHaveCount(0)
  await expect(page.getByRole('cell', { name: '이동 출고' })).toHaveCount(0)
  await expect(page.getByRole('cell', { name: '이동 입고' })).toHaveCount(0)
  await expectNoHqLeftovers(page)
})

test('게스트 실사는 장부와 세고 차이를 남긴다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '발주·검수 더 보기' }).click()
  await page.getByLabel('명령').selectOption('adjust_stock')
  await expect(page.getByText('장부 7 · 맞음')).toBeVisible()
  await expect(page.getByText('실사 차이')).toHaveCount(0)
  await page.getByPlaceholder('이름을 치세요').fill('샘플 복사용지')
  await page.getByLabel('실사 수량').fill('6')
  await expect(page.getByText('장부 7 · 차이 -1 · 확정 후 6')).toBeVisible()
  await page.getByLabel('실사 사유').fill('견본파손')
  await page.getByRole('button', { name: '실사 조정' }).click()
  await expect(page.getByText('저장했습니다. (실사 조정)')).toBeVisible()
  await expect(page.getByRole('button', { name: '샘플창고 현재고 6' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '재고현황 0' })).toHaveCount(0)
  await expectNoHqLeftovers(page)
})

test('게스트 반납은 원반출을 넘지 못한다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByLabel('명령').selectOption('post_issue')
  await page.getByPlaceholder('이름을 치세요').fill('샘플 복사용지')
  await page.getByLabel('수량', { exact: true }).fill('1')
  await page.getByLabel('반출 성명').fill('견본 김대리')
  await page.getByRole('button', { name: '반출', exact: true }).click()
  await expect(page.getByText('저장했습니다. (반출)')).toBeVisible()
  await page.getByLabel('명령').selectOption('post_return')
  await expect(page.getByText('견본 김대리 반출 · 반납 가능 1')).toBeVisible()
  await expect(page.getByText('반납 가능 0')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '반납 가능 0' })).toHaveCount(0)
  await page.getByLabel('수량', { exact: true }).fill('2')
  await page.getByRole('button', { name: '반납', exact: true }).click()
  await expect(page.getByText('반출 수량을 초과해 반납할 수 없습니다.')).toBeVisible()
  await page.getByLabel('수량', { exact: true }).fill('1')
  await expect(page.getByText('현재고 6 · 확정 후 7')).toBeVisible()
  await page.getByRole('button', { name: '반납', exact: true }).click()
  await expect(page.getByText('저장했습니다. (반납)')).toBeVisible()
  await expect(page.getByText('견본 김대리 반출 · 다 돌아왔습니다.')).toBeVisible()
  await expectNoHqLeftovers(page)
})

test('게스트 반출 기한이 지나면 반납 기한을 보여 준다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('heading', { name: /반납 기한/ })).toHaveCount(0)
  await page.getByLabel('명령').selectOption('post_issue')
  await page.getByPlaceholder('이름을 치세요').fill('샘플 복사용지')
  await page.getByLabel('수량', { exact: true }).fill('1')
  await page.getByLabel('반출 성명').fill('견본 김대리')
  await page.getByLabel('메모').fill('샘플 반출 메모')
  await page.getByLabel('반납 예정일').fill('2026-01-01')
  await page.getByRole('button', { name: '반출', exact: true }).click()
  await expect(page.getByText('저장했습니다. (반출)')).toBeVisible()
  await expect(page.getByRole('heading', { name: '반납 기한 1' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '반납 기한 0' })).toHaveCount(0)
  await page.getByRole('button', { name: '견본 김대리 · 샘플 복사용지 · 기한 지남 2026-01-01' }).click()
  await expect(page.getByLabel('명령')).toHaveValue('post_return')
  await page.getByRole('button', { name: '반납', exact: true }).click()
  await expect(page.getByText('저장했습니다. (반납)')).toBeVisible()
  await expect(page.getByRole('heading', { name: /반납 기한/ })).toHaveCount(0)
  await expectNoHqLeftovers(page)
})

test('게스트 수령은 정상만 현재고에 넣고 여러 차례 진행을 보여 준다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.locator('summary').filter({ hasText: '발주 기록' }).click()
  await expect(page.getByRole('heading', { name: '납기 지남 1' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '납기 지남 0' })).toHaveCount(0)
  await expect(page.getByRole('cell', { name: 'ORD-DEMO-01' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '견본임대' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '샘플 복사용지 · 박스 · 일반 비품' }).first()).toBeVisible()
  await expect(page.getByRole('cell', { name: '미수령', exact: true })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: '미수령' })).toBeVisible()
  await expect(page.getByText('잔량 0')).toHaveCount(0)
  await expect(page.getByText('미수령 0')).toHaveCount(0)
  await page.getByRole('button', { name: '발주·검수 더 보기' }).click()
  await page.getByLabel('명령').selectOption('post_receipt')
  await expect(page.getByText('정상만 현재고에 들어갑니다.')).toBeVisible()
  await expect(page.getByRole('heading', { name: '불량 0' })).toHaveCount(0)
  await page.getByLabel('발주 번호').fill('ORD-DEMO-01')
  await page.getByPlaceholder('이름을 치세요').fill('샘플 복사용지')
  await expect(page.getByText('발주 ORD-DEMO-01 잔량 2.')).toBeVisible()
  await page.getByLabel('정상').fill('1')
  await page.getByLabel('불량').fill('1')
  await expect(page.getByText('현재고 7 · 확정 후 8')).toBeVisible()
  await expect(page.getByText('불량은 현재고에 넣지 않습니다.')).toBeVisible()
  await page.getByRole('button', { name: '수령', exact: true }).click()
  await expect(page.getByText('저장했습니다. (수령)')).toBeVisible()
  await expect(page.getByRole('button', { name: '샘플창고 현재고 8' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '검수 불량' })).toBeVisible()
  await expect(page.getByText('발주 ORD-DEMO-01 잔량 1.')).toBeVisible()
  const records = page.locator('summary').filter({ hasText: '발주 기록' })
  if (!(await page.getByRole('cell', { name: '부분수령' }).isVisible())) {
    await records.click()
  }
  await expect(page.getByRole('cell', { name: '부분수령' })).toBeVisible()
  await page.getByLabel('정상').fill('1')
  await page.getByLabel('불량').fill('0')
  await page.getByRole('button', { name: '수령', exact: true }).click()
  await expect(page.getByText('저장했습니다. (수령)')).toBeVisible()
  await expect(page.getByRole('button', { name: '샘플창고 현재고 9' })).toBeVisible()
  await expect(page.getByText('이 발주는 다 받았습니다.')).toBeVisible()
  if (!(await page.getByRole('cell', { name: '수령완료' }).isVisible())) {
    await records.click()
  }
  await expect(page.getByRole('cell', { name: '수령완료' })).toBeVisible()
  await expect(page.getByRole('heading', { name: /납기 지남/ })).toHaveCount(0)
  await expect(page.getByText('잔량 0')).toHaveCount(0)
  await expect(page.getByText('미수령 0')).toHaveCount(0)
  await expectNoHqLeftovers(page)
})

test('게스트 출고는 현재고를 줄인다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '발주·검수 더 보기' }).click()
  await page.getByLabel('명령').selectOption('post_outbound')
  await expect(page.getByText('출고하면 현재고가 줄어듭니다. 사람 이름은 적지 않습니다.')).toBeVisible()
  await expect(page.getByLabel('반출 성명')).toHaveCount(0)
  await page.getByPlaceholder('이름을 치세요').fill('샘플 복사용지')
  await page.getByLabel('수량', { exact: true }).fill('99')
  await page.getByRole('button', { name: '출고', exact: true }).click()
  await expect(page.getByText('현재고를 초과해 출고할 수 없습니다.')).toBeVisible()
  await page.getByLabel('수량', { exact: true }).fill('1')
  await expect(page.getByText('현재고 7 · 확정 후 6')).toBeVisible()
  await page.getByLabel('메모').fill('샘플 출고 메모')
  await page.getByRole('button', { name: '출고', exact: true }).click()
  await expect(page.getByText('저장했습니다. (출고)')).toBeVisible()
  await expect(page.getByRole('button', { name: '샘플창고 현재고 6' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '출고', exact: true })).toBeVisible()
  await expect(page.getByText('샘플 출고 메모')).toBeVisible()
  await expectNoHqLeftovers(page)
})

test('게스트 책상 수령은 현재고 없이 자산이 된다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '발주·검수 더 보기' }).click()
  await page.getByLabel('명령').selectOption('draft_order')
  await page.getByLabel('발주 번호').fill('ORD-AST-01')
  await page.getByPlaceholder('이름을 치세요').first().fill('샘플 책상')
  await page.getByLabel('수량', { exact: true }).first().fill('1')
  await page.getByRole('button', { name: '품목 줄 추가', exact: true }).click()
  await page.getByPlaceholder('이름을 치세요').nth(1).fill('샘플 복사용지')
  await page.getByRole('button', { name: '발주 초안' }).click()
  await expect(page.getByText('저장했습니다. (발주 초안)')).toBeVisible()
  await page.getByLabel('명령').selectOption('confirm_order')
  await page.getByRole('button', { name: '발주 확정' }).click()
  await expect(page.getByText('저장했습니다. (발주 확정)')).toBeVisible()
  await page.getByLabel('명령').selectOption('post_receipt')
  await expect(page.getByText('수령하면 현재고 없이 자리의 물건으로 등록됩니다.')).toBeVisible()
  await expect(page.getByText('발주 ORD-AST-01 잔량 1.')).toBeVisible()
  await expect(page.getByLabel('불량')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '불량 0' })).toHaveCount(0)
  await page.getByRole('button', { name: '수령', exact: true }).click()
  await expect(page.getByText('샘플 책상 1건을 자산으로 등록했습니다.')).toBeVisible()
  await expect(page.getByRole('button', { name: '샘플창고 현재고 7' })).toBeVisible()
  await expectNoHqLeftovers(page)
  await page.getByRole('link', { name: '자산', exact: true }).click()
  await expect(page.getByRole('heading', { name: '회사 자산 3' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('cell', { name: '수령' }).click()
  await expect(page.getByText('구매 원본 발주 ORD-AST-01')).toBeVisible()
  await expect(page.getByRole('button', { name: 'PNG 받기' })).toBeVisible()
  await page.getByLabel('모델').fill('견본 수령 책상')
  await page.getByLabel('현재 자리').fill('샘플 3층')
  await page.getByRole('button', { name: '자산 정보 저장' }).click()
  await expect(page.getByText('자산 정보를 저장했습니다.')).toBeVisible()
  await expect(page.getByText('직원에게 배정하지 않았습니다.')).toBeVisible()
  await expect(page.getByRole('cell', { name: '견본 수령 책상' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '회사 자산 0' })).toHaveCount(0)
  await page.getByRole('link', { name: 'QR로 상세 보기' }).click()
  await expect(page.getByRole('heading', { name: /샘플 책상/ })).toBeVisible({ timeout: 20000 })
  await expect(page.getByText('견본 수령 책상')).toBeVisible()
  await expect(page.getByText('샘플 3층')).toBeVisible()
  await expect(page.getByRole('heading', { name: '이력 0' })).toHaveCount(0)
  await expectNoHqLeftovers(page)
})

test('게스트 구매요청은 바로 저장하고 발주 잔량을 지킨다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('heading', { name: /구매요청/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: '구매요청 0' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /REQ-DEMO-01/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /REQ-DEMO-01.*미발주/ })).toBeVisible()
  await expect(page.getByRole('button', { name: '결재' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '결재' })).toHaveCount(0)
  await expect(page.getByText('반려', { exact: true })).toHaveCount(0)
  await expect(page.getByText('재요청', { exact: true })).toHaveCount(0)
  await page.getByLabel('요청자').fill('견본청소')
  await page.getByLabel('목적').fill('샘플 청소 용품')
  await page.getByLabel('요청량').fill('3')
  await page.getByPlaceholder('요청 품목').first().fill('샘플 복사용지')
  await expect(page.getByRole('button', { name: '요청 첨부' })).toBeVisible()
  await page.getByLabel('요청 원본').setInputFiles({
    name: '견본요청.png',
    mimeType: 'image/png',
    buffer: Buffer.from([0x89, 0x50, 0x4e, 0x47]),
  })
  await page.getByRole('button', { name: '요청 저장' }).click()
  await expect(page.getByText('구매요청을 저장했습니다.')).toBeVisible()
  await expect(page.getByRole('button', { name: '견본요청.png', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /REQ-DEMO-01/ }).click()
  await expect(page.getByLabel('연결 요청')).toHaveValue('REQ-DEMO-01')
  await page.getByLabel('발주 번호').fill('ORD-REQ-01')
  await page.getByLabel('수량', { exact: true }).fill('11')
  await page.getByRole('button', { name: '발주 초안' }).click()
  await expect(page.getByText('요청 잔량을 초과해 발주할 수 없습니다.')).toBeVisible()
  await page.getByLabel('수량', { exact: true }).fill('2')
  await page.getByRole('button', { name: '발주 초안' }).click()
  await expect(page.getByText('저장했습니다. (발주 초안)')).toBeVisible()
  await expect(page.getByRole('button', { name: /REQ-DEMO-01.*부분발주/ })).toBeVisible()
  await expect(page.getByText('잔량 0')).toHaveCount(0)
  await expect(page.getByText('미발주 0')).toHaveCount(0)
  await expectNoHqLeftovers(page)
})

test('게스트 빈 QR은 샘플 품목만 넣고 지정 PC를 건드리지 않는다', async ({ page }) => {
  await page.goto(`/guest/q/${GUEST_BLANK_QR_ID}`)
  await expect(page.getByRole('heading', { name: '자산 정보 입력' })).toBeVisible({ timeout: 20000 })
  await page.getByLabel('품목').selectOption('샘플 책상')
  await page.getByLabel('위치').fill('샘플 2층')
  await page.getByRole('button', { name: '저장' }).click()
  await expect(page.getByText('샘플에 저장했습니다. 지정 PC 원본은 건드리지 않습니다.')).toBeVisible()
  await expectNoHqLeftovers(page)
})

test('게스트 묶인 QR은 샘플 자산만 보여 준다', async ({ page }) => {
  await page.goto(`/guest/q/${GUEST_DESK_QR_ID}`)
  await expect(page.getByRole('heading', { name: /샘플 책상/ })).toBeVisible({ timeout: 20000 })
  await expect(page.getByText('지정 PC 원본은 건드리지 않습니다')).toBeVisible()
  await expect(page.getByText('견본 김대리')).toBeVisible()
  await page.goto(`/guest/q/${GUEST_PC_QR_ID}`)
  await expect(page.getByRole('heading', { name: /샘플 컴퓨터/ })).toBeVisible({ timeout: 20000 })
  const missing = '11111111-1111-4111-8111-111111111111'
  await page.goto(`/guest/q/${missing}`)
  await expect(page.getByText('이 QR은 샘플에서 만든 빈 QR이 아닙니다.')).toBeVisible()
  await expectNoHqLeftovers(page)
})

test('로그아웃 정상 UUID QR은 로그인만 안내한다', async ({ page }) => {
  await page.goto(`/q/${GUEST_BLANK_QR_ID}`)
  await expect(page.getByText('빈 QR을 읽었습니다. 로그인 후')).toBeVisible()
  const login = page.getByRole('main').getByRole('link', { name: '로그인' })
  await expect(login).toBeVisible()
  const href = (await login.getAttribute('href')) ?? ''
  expect(href).toContain('/login')
  expect(href).toContain(GUEST_BLANK_QR_ID)
  expect(href).not.toContain('ops')
  expect(href).not.toContain('http')
})
