import { expect, test } from '@playwright/test'
import { GUEST_BLANK_QR_ID } from '../src/lib/guest/seed'
import { expectNoHqLeftovers, trackSupabaseMutations } from './helpers'

test('게스트 기준정보 부서·품목·직원을 저장하고 영어 상태를 두지 않는다', async ({ page }) => {
  const writes = trackSupabaseMutations(page)
  await page.goto('/guest/master')
  await expect(page.getByRole('heading', { name: '기준정보' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '부서', exact: true }).click()
  await page.getByPlaceholder('부서 이름').fill('샘플품질')
  await page.getByRole('button', { name: '추가', exact: true }).click()
  await expect(page.getByText('저장했습니다. (부서)')).toBeVisible()
  await expect(page.getByText('샘플품질')).toBeVisible()
  await page.getByRole('button', { name: '품목' }).click()
  await page.getByPlaceholder('품목 이름').fill('샘플클립')
  await page.getByRole('button', { name: '추가', exact: true }).click()
  await expect(page.getByText('저장했습니다. (품목)')).toBeVisible()
  await page.getByRole('button', { name: '직원', exact: true }).click()
  await page.getByPlaceholder('직원 이름').fill('견본 테스트')
  await page.getByLabel('직원번호').fill('G-001')
  await page.getByLabel('직위').fill('대리')
  await page.getByLabel('입사일').fill('2026-10-01')
  await page.getByRole('button', { name: '추가', exact: true }).click()
  await expect(page.getByText('저장했습니다. (직원)')).toBeVisible()
  const added = page.getByRole('row', { name: /견본 테스트/ })
  await expect(added).toContainText('G-001')
  await expect(added).toContainText('대리')
  await expect(added).toContainText('2026-10-01')
  await expectNoHqLeftovers(page)
  expect(writes).toEqual([])
})

test('게스트 반출은 견본 이름으로 저장하고 중앙 쓰기를 하지 않는다', async ({ page }) => {
  const writes = trackSupabaseMutations(page)
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByLabel('명령').selectOption('post_issue')
  await page.getByPlaceholder('이름을 치세요').fill('샘플 복사용지')
  await page.getByLabel('수량').fill('1')
  await expect(page.getByText('현재고 7 · 확정 후 6')).toBeVisible()
  await page.getByLabel('반출 성명').fill('견본 김대리')
  await page.getByLabel('반출 부서').fill('샘플품질')
  await page.getByLabel('반출 목적').fill('샘플 청소')
  await page.getByLabel('반납 예정일').fill('2026-10-10')
  await page.getByLabel('반출 첨부').setInputFiles({
    name: '견본반출.png',
    mimeType: 'image/png',
    buffer: Buffer.from([0x89, 0x50, 0x4e, 0x47]),
  })
  await page.getByRole('button', { name: '반출', exact: true }).click()
  await expect(page.getByText('저장했습니다. (반출)')).toBeVisible()
  await expect(page.getByRole('cell', { name: '견본 김대리' })).toBeVisible()
  await expect(page.getByText('샘플품질')).toBeVisible()
  await expect(page.getByText('샘플 청소')).toBeVisible()
  await expect(page.getByText('반납 예정 2026-10-10')).toBeVisible()
  await expect(page.getByText('견본반출.png')).toBeVisible()
  await page.getByLabel('명령').selectOption('post_return')
  await page.getByRole('button', { name: '반납', exact: true }).click()
  await expect(page.getByText('저장했습니다. (반납)')).toBeVisible()
  await page.getByRole('cell', { name: '반납 입고' }).click()
  await expect(page.getByRole('button', { name: '원거래로' })).toBeVisible()
  await expect(page.getByText('반출 · 견본 김대리 · 샘플품질 · 샘플 복사용지 · 1 · 박스 · 샘플 청소 · 샘플창고')).toBeVisible()
  await page.getByRole('button', { name: '원거래로' }).click()
  await expect(page.getByRole('button', { name: '반납으로' })).toBeVisible()
  await expect(page.getByText('거래 번호')).toHaveCount(0)
  await expect(page.getByText(/직전 거래:/)).toHaveCount(0)
  await expectNoHqLeftovers(page)
  expect(writes).toEqual([])
})

test('게스트 반출은 현재고를 넘지 못한다', async ({ page }) => {
  await page.goto('/guest/stock')
  await expect(page.getByRole('heading', { name: '구매·재고' })).toBeVisible({ timeout: 20000 })
  await page.getByLabel('명령').selectOption('post_issue')
  await page.getByPlaceholder('이름을 치세요').fill('샘플 복사용지')
  await page.getByLabel('수량', { exact: true }).fill('99')
  await page.getByLabel('반출 성명').fill('견본 김대리')
  await expect(page.getByLabel('초과 사유')).toHaveCount(0)
  await page.getByRole('button', { name: '반출', exact: true }).click()
  await expect(page.getByText('현재고를 초과해 반출할 수 없습니다.')).toBeVisible()
})

test('게스트 계약 이름에 스크립트를 넣어도 실행되지 않는다', async ({ page }) => {
  const dialogs: string[] = []
  page.on('dialog', (dialog) => {
    dialogs.push(dialog.message())
    void dialog.dismiss()
  })
  await page.goto('/guest/contracts')
  await expect(page.getByRole('heading', { name: '계약' }).first()).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '새 초안' }).click()
  await page.getByLabel('계약명').fill('<img src=x onerror=alert(1)>')
  await page.getByLabel('상대방').fill('<script>alert(1)</script>')
  await page.getByRole('button', { name: '초안 저장' }).click()
  await expect(page.getByText('계약 초안을 저장했습니다.')).toBeVisible()
  await expect(page.getByRole('heading', { name: '<img src=x onerror=alert(1)>' })).toBeVisible()
  expect(dialogs).toEqual([])
})

test('게스트 빈 QR 위치 스크립트는 텍스트로만 남고 중앙에 쓰지 않는다', async ({ page }) => {
  const writes = trackSupabaseMutations(page)
  const dialogs: string[] = []
  page.on('dialog', (dialog) => {
    dialogs.push(dialog.message())
    void dialog.dismiss()
  })
  await page.goto(`/guest/q/${GUEST_BLANK_QR_ID}`)
  await expect(page.getByRole('heading', { name: '자산 정보 입력' })).toBeVisible({ timeout: 20000 })
  await page.getByLabel('품목').selectOption('샘플 책상')
  await page.getByLabel('위치').fill('<svg onload=alert(1)>')
  await page.getByRole('button', { name: '저장' }).click()
  await expect(page.getByText('샘플에 저장했습니다. 지정 PC 원본은 건드리지 않습니다.')).toBeVisible()
  expect(dialogs).toEqual([])
  expect(writes).toEqual([])
})

test('게스트 입퇴사는 명찰 지급과 퇴사를 기록한다', async ({ page }) => {
  await page.goto('/guest/people')
  await expect(page.getByRole('heading', { name: '직원·입퇴사' })).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('heading', { name: '기한 지남 1' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '기한 지남 0' })).toHaveCount(0)
  await page.getByRole('button', { name: /견본 김대리.*입사 중/ }).click()
  await expect(page.getByText('완료 2026-08-01').first()).toBeVisible()
  await page.getByRole('checkbox', { name: '명찰 지급' }).click()
  await expect(page.getByText('입사 프로세스: 명찰 지급 완료')).toBeVisible()
  await page.getByRole('checkbox', { name: '근로계약서' }).click()
  await expect(page.getByText('입사 서류: 근로계약서 완료')).toBeVisible()
  await page.getByRole('button', { name: /데모 이사원.*입사 중/ }).click()
  await page.getByRole('checkbox', { name: '명찰 지급' }).click()
  await expect(page.getByText('입사 프로세스: 명찰 지급 완료')).toBeVisible()
  await page.getByRole('checkbox', { name: '유니폼 지급' }).click()
  await expect(page.getByText('입사 프로세스: 유니폼 지급 완료')).toBeVisible()
  await page.getByRole('checkbox', { name: '노트북 지급' }).click()
  await expect(page.getByText('입사 프로세스: 노트북 지급 완료')).toBeVisible()
  await expect(page.getByRole('heading', { name: '퇴사 프로세스' })).toBeVisible()
  await page.getByRole('checkbox', { name: '명찰 회수' }).click()
  await expect(page.getByText('퇴사 프로세스: 명찰 회수 완료')).toBeVisible()
  await page.getByRole('checkbox', { name: '유니폼 회수' }).click()
  await expect(page.getByText('퇴사 프로세스: 유니폼 회수 완료')).toBeVisible()
  await page.getByRole('checkbox', { name: '노트북 회수' }).click()
  await expect(page.getByText('퇴사 프로세스: 노트북 회수 완료')).toBeVisible()
  await page.getByLabel('퇴사일').fill('2026-09-15')
  await page.getByRole('button', { name: '퇴사', exact: true }).click()
  await expect(page.getByText('퇴사를 기록했습니다.')).toBeVisible()
  await expect(page.getByText('퇴사 2026-09-15').first()).toBeVisible()
  await expectNoHqLeftovers(page)
})

test('게스트 자산은 이관하고 빈 QR을 만든다', async ({ page }) => {
  const writes = trackSupabaseMutations(page)
  await page.goto('/guest/assets')
  await expect(page.getByRole('heading', { name: '자산', exact: true })).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('columnheader', { name: '상태' })).toBeVisible()
  await page.getByPlaceholder('번호·품목·모델·위치·담당').fill('DEMO-DSK-01')
  await expect(page.getByRole('cell', { name: '샘플 책상' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '샘플 컴퓨터' })).toHaveCount(0)
  await page.getByPlaceholder('번호·품목·모델·위치·담당').fill('')
  await page.getByRole('cell', { name: '샘플 책상' }).click()
  await expect(page.getByRole('button', { name: '자산 목록 받기' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: '구매 원본' })).toBeVisible()
  await expect(page.getByRole('button', { name: '이력 첨부' })).toBeVisible()
  await page.getByLabel('이력 원본').setInputFiles({
    name: '견본이관.png',
    mimeType: 'image/png',
    buffer: Buffer.from([0x89, 0x50, 0x4e, 0x47]),
  })
  await page.getByLabel('위치').fill('샘플 3층')
  await page.getByRole('button', { name: '이관 저장' }).click()
  await expect(page.getByText('이관 이력을 남겼습니다. 직원에게 배정하지 않았습니다.')).toBeVisible()
  await expect(page.getByText(/부서 샘플총무/)).toBeVisible()
  await expect(page.getByText(/담당 견본 김대리/)).toBeVisible()
  await expect(page.getByRole('button', { name: '견본이관.png', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '빈 QR 만들기' }).click()
  await expect(page.getByText(/샘플 빈 QR/)).toBeVisible()
  await expectNoHqLeftovers(page)
  expect(writes).toEqual([])
})

test('게스트 자산은 공급사에 반품하고 회사 자산에서 뺀다', async ({ page }) => {
  const writes = trackSupabaseMutations(page)
  await page.goto('/guest/assets')
  await expect(page.getByRole('heading', { name: '자산', exact: true })).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('heading', { name: '공급사 반품 0' })).toHaveCount(0)
  await page.getByRole('cell', { name: '샘플 책상' }).click()
  await page.getByLabel('구분').selectOption('supplier_return')
  await page.getByLabel('사유').fill('샘플 반품')
  await page.getByLabel('이력 원본').setInputFiles({
    name: '견본반품.png',
    mimeType: 'image/png',
    buffer: Buffer.from([0x89, 0x50, 0x4e, 0x47]),
  })
  await page.getByRole('button', { name: '공급사 반품 저장' }).click()
  await expect(page.getByText('공급사 반품 이력을 남겼습니다. 직원에게 배정하지 않았습니다.')).toBeVisible()
  await expect(page.getByRole('heading', { name: '공급사 반품 1' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '회사 자산 1' })).toBeVisible()
  await expect(page.getByText('샘플 책상')).toBeVisible()
  await expectNoHqLeftovers(page)
  expect(writes).toEqual([])
})

test('게스트 기준정보 창고·거래처를 저장하고 빈 필드 키는 막는다', async ({ page }) => {
  await page.goto('/guest/master')
  await expect(page.getByRole('heading', { name: '기준정보' })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '창고', exact: true }).click()
  await page.getByPlaceholder('창고 이름').fill('샘플품질창고')
  await page.getByLabel('위치').fill('샘플 3층')
  await page.getByRole('button', { name: '추가', exact: true }).click()
  await expect(page.getByText('저장했습니다. (창고)')).toBeVisible()
  await expect(page.getByText('샘플 3층')).toBeVisible()
  await page.getByRole('button', { name: '거래처' }).click()
  await page.getByPlaceholder('거래처 이름').fill('견본거래')
  await page.getByRole('button', { name: '추가', exact: true }).click()
  await expect(page.getByText('저장했습니다. (거래처)')).toBeVisible()
  await page.getByRole('button', { name: '필드' }).click()
  await page.getByPlaceholder('라벨').fill('샘플필드')
  await page.getByRole('button', { name: '추가', exact: true }).click()
  await expect(page.getByText('필드 키를 입력하세요.')).toBeVisible()
  await expectNoHqLeftovers(page)
})
